## deminfhelper_template.yml
# STAIRWAYPLOT
path_to_stairwayplot2: workflow/modules/popsize/bin/stairway_plot_es/
blueprint_template: workflow/modules/popsize/config/swp2_template.blueprint
## DADI
lower_bound: 1, 1, 0.05, 0.01
p0: 0.01, 0.001, 0.01, 0.01
upper_bound: 10, 4, 0.1, 10
# MSMC2 default args
msmc2_kwargs: -i 25; -p 1*2+25*1+1*2+1*3
# PSMC default args
psmc_kwargs: -N25 -t15 -r5 -p "4+25*2+4+6"
# Filter contig
contig_filter: CM.*
plot_psmc_kwargs: -x 10**5 -X 2800000
